[package]
name = "aflak_plot"
version = "0.0.3"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Plotting library using imgui made for aflak"
license = "GPL-3.0-only"

[dependencies]
glium = { git = "https://github.com/malikolivier/glium", rev = "f36ceca3864171e8217dc60085750e2af9beec82" }
imgui = { path = "../../imgui-rs", version = "0.3.0-pre" }
imgui-glium-renderer = { path = "../../imgui-rs/imgui-glium-renderer", version = "0.3.0-pre" }
ndarray = "0.12"

[dev-dependencies]
aflak_imgui_glium_support = { path = "../imgui_glium_support", version = "0.0.3" }
